[theme]
# Color de fondo central (Blanco limpio y luminoso)
backgroundColor = "#FFFFFF"

# Color de la barra lateral (Azul Niebla suave: máxima legibilidad para textos y cajas)
secondaryBackgroundColor = "#E2E8F0"

# Color del texto principal (Gris pizarra oscuro, muy legible)
textColor = "#1E293B"

# Color de los botones y elementos activos (Azul Prusia institucional)
primaryColor = "#1E40AF"

# Tipografía (Serif clásica para títulos académicos elegantes y humanos)
font = "serif"
